chorus-ubi-pipeline:
  source:
    otel_trace_source:
      port: 21890
      ssl: false
  buffer:
    bounded_blocking:
      buffer_size: 50
      batch_size: 1      
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        index_type: custom
        index: ubi_events
    - stdout:
